name: Trigger API Route Every 10 Minutes

on:
  schedule:
    # This schedule runs every 10 minutes
    - cron: "*/10 * * * *"

jobs:
  triggerAPI:
    runs-on: ubuntu-latest
    steps:
      - name: Call API Endpoint
        run: |
          curl -X POST https://crypt-razlevio.vercel.app/api/crypto
